export const students = [
 // class o
  {
    id: 0,
    name: "Macaulay Morgana",
    enrolled_courses: [0],
    age: 20,
    date_enrolled: 0,
  },
  {
    id: 1,
    name: "Marion Kristie",
    enrolled_courses: [0],
    age: 17,
    date_enrolled: 0,
  },
  {
    id: 2,
    name: "Winton Kayden",
    enrolled_courses: [0],
    age: 25,
    date_enrolled: 0,
  },
  {
    id: 3,
    name: "Gibson Bethel",
    enrolled_courses: [0],
    age: 32,
    date_enrolled: 0,
  },
  // class 1
  {
    id: 4,
    name: "Suellen Albie",
    enrolled_courses: [1],
    age: 10,
    date_enrolled: 0,
  },
  {
    id: 5,
    name: "Weldon Jennie",
    enrolled_courses: [1],
    age: 11,
    date_enrolled: 0,
  },
  {
    id: 6,
    name: "Grier Annabella",
    enrolled_courses: [1],
    age: 9,
    date_enrolled: 0,
  },
  {
    id: 7,
    name: "Elicia Candice",
    enrolled_courses: [1],
    age: 0,
    date_enrolled: 0,
  },
  {
    id: 8,
    name: "Leigh Jon",
    enrolled_courses: [1],
    age: 10,
    date_enrolled: 0,
  },
  {
    id: 9,
    name: "Caylee Addy",
    enrolled_courses: [1],
    age: 10,
    date_enrolled: 0,
  },
  {
    id: 10,
    name: "Rosanna Quintin",
    enrolled_courses: [1],
    age: 10,
    date_enrolled: 0,
  },
  {
    id: 11,
    name: "Nyah Gaby",
    enrolled_courses: [1],
    age: 11,
    date_enrolled: 0,
  },
  // class 2
  {
    id: 12,
    name: "Deidre Elfrieda",
    enrolled_courses: [2],
    age: 0,
    date_enrolled: 0,
  },
  {
    id: 13,
    name: "Woody Clement",
    enrolled_courses: [2],
    age: 5,
    date_enrolled: 0,
  },
  {
    id: 14,
    name: "Alexus Jream",
    enrolled_courses: [2],
    age: 4,
    date_enrolled: 0,
  },
  {
    id: 15,
    name: "Lemoine Saige",
    enrolled_courses: [2],
    age: 5,
    date_enrolled: 0,
  },
  {
    id: 16,
    name: "Reed Tiana",
    enrolled_courses: [2],
    age: 5,
    date_enrolled: 0,
  },
  {
    id: 17,
    name: "Karter Leone",
    enrolled_courses: [2],
    age: 5,
    date_enrolled: 0,
  },
  {
    id: 18,
    name: "Buzz Hall",
    enrolled_courses: [2],
    age: 4,
    date_enrolled: 0,
  },
  {
    id: 19,
    name: "Andy Kelsey",
    enrolled_courses: [2],
    age: 4,
    date_enrolled: 0,
  },
  {
    id: 20,
    name: "Amy Florry",
    enrolled_courses: [2],
    age: 5,
    date_enrolled: 0,
  },
  {
    id: 21,
    name: "Julianne Paulette",
    enrolled_courses: [2],
    age: 5,
    date_enrolled: 0,
  },
  // class 3
  {
    id: 22,
    name: "Flower Hewie",
    enrolled_courses: [3],
    age: 5,
    date_enrolled: 0,
  },
  {
    id: 23,
    name: "Rebeccanne Sanford",
    enrolled_courses: [3],
    age: 0,
    date_enrolled: 0,
  },
  {
    id: 24,
    name: "Julie Hadley",
    enrolled_courses: [3],
    age: 0,
    date_enrolled: 0,
  },
  {
    id: 25,
    name: "Rafferty Calista",
    enrolled_courses: [3],
    age: 0,
    date_enrolled: 0,
  },
  {
    id: 26,
    name: "Rodolph Sid",
    enrolled_courses: [3],
    age: 0,
    date_enrolled: 0,
  },
  {
    id: 27,
    name: "Watson Emersyn",
    enrolled_courses: [3],
    age: 0,
    date_enrolled: 0,
  },
  {
    id: 28,
    name: "Placid Ashlynn",
    enrolled_courses: [3],
    age: 0,
    date_enrolled: 0,
  },
  {
    id: 29,
    name: "Lorri Laurinda",
    enrolled_courses: [3],
    age: 0,
    date_enrolled: 0,
  },
  {
    id: 30,
    name: "Lorri Laurinda",
    enrolled_courses: [3],
    age: 0,
    date_enrolled: 0,
  },
  {
    id: 31,
    name: "Lorri Laurinda",
    enrolled_courses: [4],
    age: 0,
    date_enrolled: 0,
  },
];
