import { CLASS_STATUS, classes } from "./Classes";

export const students = [
  // class 0
  {
    id: 0,
    name: "Macaulay Morgana",
    enrolled_courses: 0,
    age: 20,
    date_enrolled: "6/6/2022",
  },
  {
    id: 1,
    name: "Marion Kristie",
    enrolled_courses: 0,
    age: 17,
    date_enrolled: "6/6/2022",
  },
  {
    id: 2,
    name: "Winton Kayden",
    enrolled_courses: 0,
    age: 25,
    date_enrolled: "6/6/2022",
  },
  {
    id: 3,
    name: "Gibson Bethel",
    enrolled_courses: 0,
    age: 32,
    date_enrolled: "6/6/2022",
  },
  // class 1
  {
    id: 4,
    name: "Suellen Albie",
    enrolled_courses: 1,
    age: 10,
    date_enrolled: "6/6/2022",
  },
  {
    id: 5,
    name: "Weldon Jennie",
    enrolled_courses: 1,
    age: 11,
    date_enrolled: "6/6/2022",
  },
  {
    id: 6,
    name: "Grier Annabella",
    enrolled_courses: 1,
    age: 9,
    date_enrolled: "6/6/2022",
  },
  {
    id: 7,
    name: "Elicia Candice",
    enrolled_courses: 1,
    age: 0,
    date_enrolled: "6/6/2022",
  },
  {
    id: 8,
    name: "Leigh Jon",
    enrolled_courses: 1,
    age: 10,
    date_enrolled: "6/6/2022",
  },
  {
    id: 9,
    name: "Caylee Addy",
    enrolled_courses: 1,
    age: 10,
    date_enrolled: "6/6/2022",
  },
  {
    id: 10,
    name: "Rosanna Quintin",
    enrolled_courses: 1,
    age: 10,
    date_enrolled: "6/6/2022",
  },
  {
    id: 11,
    name: "Nyah Gaby",
    enrolled_courses: 1,
    age: 11,
    date_enrolled: "6/6/2022",
  },
  // class 2
  {
    id: 12,
    name: "Deidre Elfrieda",
    enrolled_courses: 2,
    age: 0,
    date_enrolled: "6/6/2022",
  },
  {
    id: 13,
    name: "Woody Clement",
    enrolled_courses: 2,
    age: 5,
    date_enrolled: "6/6/2022",
  },
  {
    id: 14,
    name: "Alexus Jream",
    enrolled_courses: 2,
    age: 4,
    date_enrolled: "6/6/2022",
  },
  {
    id: 15,
    name: "Lemoine Saige",
    enrolled_courses: 2,
    age: 5,
    date_enrolled: "6/6/2022",
  },
  {
    id: 16,
    name: "Reed Tiana",
    enrolled_courses: 2,
    age: 5,
    date_enrolled: "6/6/2022",
  },
  {
    id: 17,
    name: "Karter Leone",
    enrolled_courses: 2,
    age: 5,
    date_enrolled: "6/6/2022",
  },
  {
    id: 18,
    name: "Buzz Hall",
    enrolled_courses: 2,
    age: 4,
    date_enrolled: "6/6/2022",
  },
  {
    id: 19,
    name: "Andy Kelsey",
    enrolled_courses: 2,
    age: 4,
    date_enrolled: "6/6/2022",
  },
  {
    id: 20,
    name: "Amy Florry",
    enrolled_courses: 2,
    age: 5,
    date_enrolled: "6/6/2022",
  },
  {
    id: 21,
    name: "Julianne Paulette",
    enrolled_courses: 2,
    age: 5,
    date_enrolled: "6/6/2022",
  },
  // class 3
  {
    id: 22,
    name: "Flower Hewie",
    enrolled_courses: 3,
    age: 5,
    date_enrolled: "6/6/2022",
  },
  {
    id: 23,
    name: "Rebeccanne Sanford",
    enrolled_courses: 3,
    age: 0,
    date_enrolled: "6/6/2022",
  },
  {
    id: 24,
    name: "Julie Hadley",
    enrolled_courses: 3,
    age: 0,
    date_enrolled: "6/6/2022",
  },
  {
    id: 25,
    name: "Rafferty Calista",
    enrolled_courses: 3,
    age: 0,
    date_enrolled: "6/6/2022",
  },
  {
    id: 26,
    name: "Rodolph Sid",
    enrolled_courses: 3,
    age: 0,
    date_enrolled: "6/6/2022",
  },
  {
    id: 27,
    name: "Watson Emersyn",
    enrolled_courses: 3,
    age: 0,
    date_enrolled: "6/6/2022",
  },
  {
    id: 28,
    name: "Placid Ashlynn",
    enrolled_courses: 3,
    age: 0,
    date_enrolled: "6/6/2022",
  },
  {
    id: 29,
    name: "Lorri Laurinda",
    enrolled_courses: 3,
    age: 0,
    date_enrolled: "6/6/2022",
  },
  {
    id: 30,
    name: "Lorri Laurinda",
    enrolled_courses: 3,
    age: 0,
    date_enrolled: "6/6/2022",
  },
  {
    id: 31,
    name: "Aimee Floyd",
    enrolled_courses: 7,
    age: 6,
    date_enrolled: "6/6/2022",
  },
  {
    id: 32,
    name: "Craig Simpson",
    enrolled_courses: 7,
    age: 7,
    date_enrolled: "3/4/2022",
  },
  {
    id: 33,
    name: "Darnell Brock",
    enrolled_courses: 7,
    age: 7,
    date_enrolled: "7/2/2022",
  },
  {
    id: 34,
    name: "Izaiah Bradford",
    enrolled_courses: 7,
    age: 7,
    date_enrolled: "18/4/2022",
  },
  {
    id: 35,
    name: "Angel Spencer",
    enrolled_courses: 8,
    age: 6,
    date_enrolled: "6/9/2021",
  },
  {
    id: 36,
    name: "Hazel Rowland",
    enrolled_courses: 8,
    age: 7,
    date_enrolled: "7/6/2021",
  },
  {
    id: 37,
    name: "Paul Sherman",
    enrolled_courses: 8,
    age: 6,
    date_enrolled: "7/4/2020",
  },
  {
    id: 38,
    name: "Dayami Buck",
    enrolled_courses: 8,
    age: 7,
    date_enrolled: "15/7/2021",
  },
  {
    id: 39,
    name: "Maci Baker",
    enrolled_courses: 8,
    age: 7,
    date_enrolled: "23/3/2020",
  },
  {
    id: 40,
    name: "Kyan Clay",
    enrolled_courses: 9,
    age: 8,
    date_enrolled: "4/4/2022",
  },
  {
    id: 41,
    name: "Brycen Montes",
    enrolled_courses: 9,
    age: 6,
    date_enrolled: "12/10/2020",
  },
  {
    id: 42,
    name: "Bronson Kelley",
    enrolled_courses: 9,
    age: 7,
    date_enrolled: "6/13/2020",
  },
  {
    id: 43,
    name: "Immanuel Calhoun",
    enrolled_courses: 9,
    age: 6,
    date_enrolled: "6/1/2021",
  },
  {
    id: 44,
    name: "Giada Hale",
    enrolled_courses: 9,
    age: 7,
    date_enrolled: "15/3/2023",
  },
  {
    id: 45,
    name: "Sincere Perkins",
    enrolled_courses: 9,
    age: 6,
    date_enrolled: "26/11/2021",
  },
  {
    id: 46,
    name: "Miah Baird",
    enrolled_courses: 9,
    age: 6,
    date_enrolled: "7/7/2022",
  },
  {
    id: 47,
    name: "Rosa Coleman",
    enrolled_courses: 10,
    age: 46,
    date_enrolled: "26/1/2021",
  },
  {
    id: 48,
    name: "Matias Anderson",
    enrolled_courses: 10,
    age: 27,
    date_enrolled: "18/10/2022",
  },
  {
    id: 49,
    name: "Cristian Haynes",
    enrolled_courses: 10,
    age: 36,
    date_enrolled: "17/9/2020",
  },
  {
    id: 50,
    name: "Justice Molina",
    enrolled_courses: 10,
    age: 15,
    date_enrolled: "13/7/2023",
  },
  {
    id: 51,
    name: "Felicity Haas",
    enrolled_courses: 10,
    age: 36,
    date_enrolled: "15/10/2021",
  },
  {
    id: 52,
    name: "Carter Romero",
    enrolled_courses: 10,
    age: 28,
    date_enrolled: "2/4/2021",
  },
  {
    id: 53,
    name: "Marie Whitney",
    enrolled_courses: 10,
    age: 79,
    date_enrolled: "9/10/2021",
  },
  {
    id: 54,
    name: "Davion May",
    enrolled_courses: 10,
    age: 54,
    date_enrolled: "23/9/2021",
  },
  {
    id: 55,
    name: "Coleman Holloway",
    enrolled_courses: 10,
    age: 38,
    date_enrolled: "25/3/2020",
  },
  {
    id: 56,
    name: "Vaughn Madden",
    enrolled_courses: 10,
    age: 27,
    date_enrolled: "10/7/2020",
  },
  {
    id: 57,
    name: "Lucy Villegas",
    enrolled_courses: 12,
    age: 12,
    date_enrolled: "17/3/2022",
  },
  {
    id: 58,
    name: "Shayna Higgins",
    enrolled_courses: 12,
    age: 14,
    date_enrolled: "22/10/2021",
  },
  {
    id: 59,
    name: "Levi Davis",
    enrolled_courses: 12,
    age: 14,
    date_enrolled: "4/6/2022",
  },
  {
    id: 60,
    name: "Garrett Cummings",
    enrolled_courses: 12,
    age: 13,
    date_enrolled: "9/2/2022",
  },
  {
    id: 61,
    name: "Bradyn Brooks",
    enrolled_courses: 12,
    age: 13,
    date_enrolled: "11/12/2020",
  },
  {
    id: 62,
    name: "Joel Estrada",
    enrolled_courses: 13,
    age: 69,
    date_enrolled: "17/10/2023",
  },
  {
    id: 63,
    name: "Gideon Blackwell",
    enrolled_courses: 13,
    age: 35,
    date_enrolled: "8/5/2021",
  },
  {
    id: 64,
    name: "Reid Munoz",
    enrolled_courses: 13,
    age: 42,
    date_enrolled: "19/9/2021",
  },
  {
    id: 65,
    name: "Dashawn Delacruz",
    enrolled_courses: 13,
    age: 46,
    date_enrolled: "21/3/2021",
  },
  {
    id: 66,
    name: "Emilee David",
    enrolled_courses: 13,
    age: 17,
    date_enrolled: "3/4/2021",
  },
  {
    id: 67,
    name: "Isabela Vaughn",
    enrolled_courses: 14,
    age: 9,
    date_enrolled: "22/7/2022",
  },
  {
    id: 68,
    name: "Efrain Beasley",
    enrolled_courses: 14,
    age: 9,
    date_enrolled: "5/11/2022",
  },
  {
    id: 69,
    name: "Makai Page",
    enrolled_courses: 14,
    age: 9,
    date_enrolled: "10/11/2023",
  },
  {
    id: 70,
    name: "Gavin Hopkins",
    enrolled_courses: 14,
    age: 11,
    date_enrolled: "12/4/2021",
  },
  {
    id: 71,
    name: "Miracle Cole",
    enrolled_courses: 16,
    age: 10,
    date_enrolled: "3/11/2022",
  },
  {
    id: 72,
    name: "Enrique Weaver",
    enrolled_courses: 16,
    age: 11,
    date_enrolled: "5/9/2020",
  },
  {
    id: 73,
    name: "Karsyn Rogers",
    enrolled_courses: 16,
    age: 10,
    date_enrolled: "6/6/2021",
  },
  {
    id: 74,
    name: "Jocelyn Tran",
    enrolled_courses: 17,
    age: 29,
    date_enrolled: "21/8/2020",
  },
  {
    id: 75,
    name: "Dylan Boyer",
    enrolled_courses: 17,
    age: 37,
    date_enrolled: "10/4/2022",
  },
  {
    id: 76,
    name: "Michaela Velasquez",
    enrolled_courses: 17,
    age: 72,
    date_enrolled: "27/8/2020",
  },
  {
    id: 77,
    name: "Tony Pennington",
    enrolled_courses: 17,
    age: 32,
    date_enrolled: "10/7/2021",
  },
  {
    id: 78,
    name: "August Stafford",
    enrolled_courses: 17,
    age: 50,
    date_enrolled: "23/8/2020",
  },
  {
    id: 79,
    name: "Jax Vargas",
    enrolled_courses: 17,
    age: 77,
    date_enrolled: "22/8/2020",
  },
  {
    id: 80,
    name: "Finley Richardson",
    enrolled_courses: 19,
    age: 13,
    date_enrolled: "26/2/2021",
  },
  {
    id: 81,
    name: "Fletcher Ritter",
    enrolled_courses: 19,
    age: 13,
    date_enrolled: "17/2/2022",
  },
  {
    id: 82,
    name: "Theodore Rowland",
    enrolled_courses: 19,
    age: 13,
    date_enrolled: "8/9/2022",
  },
  {
    id: 83,
    name: "Jamar Jarvis",
    enrolled_courses: 19,
    age: 12,
    date_enrolled: "26/2/2020",
  },
  {
    id: 84,
    name: "Diana Hogan",
    enrolled_courses: 20,
    age: 30,
    date_enrolled: "7/3/2022",
  },
  {
    id: 85,
    name: "Rory Hammond",
    enrolled_courses: 20,
    age: 64,
    date_enrolled: "8/8/2021",
  },
  {
    id: 86,
    name: "Jasper Munoz",
    enrolled_courses: 20,
    age: 27,
    date_enrolled: "7/6/2020",
  },
  {
    id: 87,
    name: "Hadley Pugh",
    enrolled_courses: 20,
    age: 69,
    date_enrolled: "11/9/2022",
  },
  {
    id: 88,
    name: "Saul Pearson",
    enrolled_courses: 20,
    age: 79,
    date_enrolled: "26/6/2021",
  },
  {
    id: 89,
    name: "Yazmin Campos",
    enrolled_courses: 20,
    age: 58,
    date_enrolled: "18/1/2022",
  },
  {
    id: 90,
    name: "Nico Stone",
    enrolled_courses: 20,
    age: 14,
    date_enrolled: "10/3/2021",
  },
  {
    id: 91,
    name: "Jocelynn Odonnell",
    enrolled_courses: 21,
    age: 6,
    date_enrolled: "5/6/2022",
  },
  {
    id: 92,
    name: "Kaylie Fitzpatrick",
    enrolled_courses: 21,
    age: 7,
    date_enrolled: "26/4/2022",
  },
  {
    id: 93,
    name: "Charlie Holloway",
    enrolled_courses: 21,
    age: 7,
    date_enrolled: "6/2/2021",
  },
  {
    id: 94,
    name: "Savannah Leach",
    enrolled_courses: 21,
    age: 7,
    date_enrolled: "16/3/2020",
  },
  {
    id: 95,
    name: "Zachery Chapman",
    enrolled_courses: 21,
    age: 7,
    date_enrolled: "16/3/2020",
  },
  {
    id: 96,
    name: "Emelia Doyle",
    enrolled_courses: 21,
    age: 7,
    date_enrolled: "5/8/2022",
  },
  {
    id: 97,
    name: "Kenley Rodgers",
    enrolled_courses: 21,
    age: 8,
    date_enrolled: "1/9/2022",
  },
  {
    id: 98,
    name: "Davon Mckinney",
    enrolled_courses: 21,
    age: 7,
    date_enrolled: "17/9/2023",
  },
  {
    id: 99,
    name: "Haylee Summers",
    enrolled_courses: 23,
    age: 8,
    date_enrolled: "16/4/2020",
  },
  {
    id: 100,
    name: "Giana Pacheco",
    enrolled_courses: 23,
    age: 7,
    date_enrolled: "6/1/2023",
  },
  {
    id: 101,
    name: "Regan Decker",
    enrolled_courses: 23,
    age: 6,
    date_enrolled: "9/8/2022",
  },
  {
    id: 102,
    name: "Paityn Mcdaniel",
    enrolled_courses: 24,
    age: 41,
    date_enrolled: "11/12/2022",
  },
  {
    id: 103,
    name: "Amelie Hernandez",
    enrolled_courses: 24,
    age: 39,
    date_enrolled: "23/3/2022",
  },
  {
    id: 104,
    name: "Kyra Aguilar",
    enrolled_courses: 24,
    age: 38,
    date_enrolled: "5/2/2021",
  },
  {
    id: 105,
    name: "Tiara Valencia",
    enrolled_courses: 24,
    age: 67,
    date_enrolled: "11/7/2023",
  },
  {
    id: 106,
    name: "Madisyn Hobbs",
    enrolled_courses: 25,
    age: 26,
    date_enrolled: "20/9/2023",
  },
  {
    id: 107,
    name: "Casey Benson",
    enrolled_courses: 25,
    age: 39,
    date_enrolled: "16/6/2023",
  },
  {
    id: 108,
    name: "Jaylene Schroeder",
    enrolled_courses: 25,
    age: 36,
    date_enrolled: "20/6/2021",
  },
  {
    id: 109,
    name: "Remington Little",
    enrolled_courses: 25,
    age: 41,
    date_enrolled: "10/10/2022",
  },
  {
    id: 110,
    name: "Nyla Wolfe",
    enrolled_courses: 25,
    age: 24,
    date_enrolled: "8/10/2022",
  },
  {
    id: 111,
    name: "Angel Harmon",
    enrolled_courses: 26,
    age: 13,
    date_enrolled: "3/11/2020",
  },
  {
    id: 112,
    name: "Lincoln Mckay",
    enrolled_courses: 26,
    age: 13,
    date_enrolled: "27/11/2022",
  },
  {
    id: 113,
    name: "Eliza Yates",
    enrolled_courses: 26,
    age: 12,
    date_enrolled: "2/7/2021",
  },
  {
    id: 114,
    name: "Kasey Sparks",
    enrolled_courses: 26,
    age: 13,
    date_enrolled: "28/9/2021",
  },
  {
    id: 115,
    name: "Hailey Kline",
    enrolled_courses: 26,
    age: 13,
    date_enrolled: "22/7/2021",
  },
  {
    id: 116,
    name: "Paityn Juarez",
    enrolled_courses: 27,
    age: 9,
    date_enrolled: "26/8/2021",
  },
  {
    id: 117,
    name: "Keira Hanson",
    enrolled_courses: 27,
    age: 10,
    date_enrolled: "4/6/2021",
  },
  {
    id: 118,
    name: "Trace Cardenas",
    enrolled_courses: 27,
    age: 10,
    date_enrolled: "21/3/2020",
  },
  {
    id: 119,
    name: "Wade Durham",
    enrolled_courses: 27,
    age: 11,
    date_enrolled: "27/4/2022",
  },
  {
    id: 120,
    name: "Cory Owens",
    enrolled_courses: 27,
    age: 11,
    date_enrolled: "3/11/2022",
  },
  {
    id: 121,
    name: "Angela Salas",
    enrolled_courses: 27,
    age: 9,
    date_enrolled: "7/9/2023",
  },
  {
    id: 122,
    name: "Jonathon Jennings",
    enrolled_courses: 27,
    age: 10,
    date_enrolled: "25/10/2020",
  },
  {
    id: 123,
    name: "Brenton Anthony",
    enrolled_courses: 28,
    age: 74,
    date_enrolled: "2/4/2022",
  },
  {
    id: 124,
    name: "Alisa Randall",
    enrolled_courses: 28,
    age: 71,
    date_enrolled: "7/10/2021",
  },
  {
    id: 125,
    name: "Jesse Bradford",
    enrolled_courses: 28,
    age: 65,
    date_enrolled: "19/3/2021",
  },
  {
    id: 126,
    name: "Dayami Underwood",
    enrolled_courses: 28,
    age: 34,
    date_enrolled: "9/13/2022",
  },
  {
    id: 127,
    name: "Amelie Jensen",
    enrolled_courses: 29,
    age: 43,
    date_enrolled: "19/7/2022",
  },
  {
    id: 128,
    name: "Ezekiel Berry",
    enrolled_courses: 29,
    age: 70,
    date_enrolled: "13/3/2023",
  },
  {
    id: 129,
    name: "Sage Sampson",
    enrolled_courses: 29,
    age: 69,
    date_enrolled: "27/10/2022",
  },
  {
    id: 130,
    name: "Baylee Carr",
    enrolled_courses: 29,
    age: 47,
    date_enrolled: "21/13/2022",
  },
  {
    id: 131,
    name: "Kamari Ruiz",
    enrolled_courses: 29,
    age: 22,
    date_enrolled: "4/1/2022",
  },
  {
    id: 132,
    name: "Van Andersen",
    enrolled_courses: 29,
    age: 20,
    date_enrolled: "2/4/2021",
  },
  {
    id: 133,
    name: "Jazmyn Boyle",
    enrolled_courses: 29,
    age: 28,
    date_enrolled: "4/4/2022",
  },
  {
    id: 134,
    name: "Carson Norton",
    enrolled_courses: 29,
    age: 48,
    date_enrolled: "16/4/2021",
  },
  {
    id: 135,
    name: "Meredith Orozco",
    enrolled_courses: 30,
    age: 54,
    date_enrolled: "6/10/2022",
  },
  {
    id: 136,
    name: "Arjun Kennedy",
    enrolled_courses: 30,
    age: 34,
    date_enrolled: "19/1/2022",
  },
  {
    id: 137,
    name: "Stephany Carlson",
    enrolled_courses: 30,
    age: 35,
    date_enrolled: "24/12/2020",
  },
  {
    id: 138,
    name: "Jesse Lin",
    enrolled_courses: 30,
    age: 20,
    date_enrolled: "17/5/2020",
  },
  {
    id: 139,
    name: "Eric Baird",
    enrolled_courses: 31,
    age: 79,
    date_enrolled: "9/11/2022",
  },
  {
    id: 140,
    name: "Ronnie Hardy",
    enrolled_courses: 31,
    age: 62,
    date_enrolled: "28/6/2022",
  },
  {
    id: 141,
    name: "Jayda Allison",
    enrolled_courses: 31,
    age: 15,
    date_enrolled: "9/6/2020",
  },
  {
    id: 142,
    name: "Angel Adkins",
    enrolled_courses: 31,
    age: 72,
    date_enrolled: "28/5/2023",
  },
  {
    id: 143,
    name: "Kinley Pearson",
    enrolled_courses: 31,
    age: 17,
    date_enrolled: "22/3/2022",
  },
  {
    id: 144,
    name: "Evelyn Saunders",
    enrolled_courses: 32,
    age: 11,
    date_enrolled: "14/10/2020",
  },
  {
    id: 145,
    name: "Ashlyn Bennett",
    enrolled_courses: 32,
    age: 11,
    date_enrolled: "5/6/2021",
  },
  {
    id: 146,
    name: "Franklin Haas",
    enrolled_courses: 32,
    age: 10,
    date_enrolled: "13/1/2023",
  },
  {
    id: 147,
    name: "Harmony Lowery",
    enrolled_courses: 32,
    age: 11,
    date_enrolled: "6/12/2023",
  },
  {
    id: 148,
    name: "Omari Santana",
    enrolled_courses: 32,
    age: 9,
    date_enrolled: "26/5/2020",
  },
  {
    id: 149,
    name: "Janet Ferguson",
    enrolled_courses: 32,
    age: 10,
    date_enrolled: "19/2/2022",
  },
  {
    id: 150,
    name: "Adonis Mcclure",
    enrolled_courses: 32,
    age: 11,
    date_enrolled: "26/13/2021",
  },
  {
    id: 151,
    name: "Dustin Garcia",
    enrolled_courses: 33,
    age: 6,
    date_enrolled: "24/11/2022",
  },
  {
    id: 152,
    name: "Gemma Henderson",
    enrolled_courses: 33,
    age: 6,
    date_enrolled: "13/3/2022",
  },
  {
    id: 153,
    name: "Selina Schmitt",
    enrolled_courses: 33,
    age: 7,
    date_enrolled: "16/1/2022",
  },
  {
    id: 154,
    name: "Luca Walters",
    enrolled_courses: 33,
    age: 8,
    date_enrolled: "7/10/2021",
  },
  {
    id: 155,
    name: "River Spencer",
    enrolled_courses: 34,
    age: 8,
    date_enrolled: "26/9/2022",
  },
  {
    id: 156,
    name: "Dominique Baker",
    enrolled_courses: 34,
    age: 8,
    date_enrolled: "19/6/2021",
  },
  {
    id: 157,
    name: "Adriel Patel",
    enrolled_courses: 34,
    age: 6,
    date_enrolled: "6/4/2023",
  },
  {
    id: 158,
    name: "Paige Summers",
    enrolled_courses: 34,
    age: 6,
    date_enrolled: "22/4/2021",
  },
  {
    id: 159,
    name: "Caleb Rios",
    enrolled_courses: 34,
    age: 6,
    date_enrolled: "23/8/2023",
  },
  {
    id: 160,
    name: "Ariel Lopez",
    enrolled_courses: 34,
    age: 8,
    date_enrolled: "27/9/2022",
  },
  {
    id: 161,
    name: "Sheldon Cain",
    enrolled_courses: 34,
    age: 6,
    date_enrolled: "13/6/2021",
  },
  {
    id: 162,
    name: "Janiyah Oneal",
    enrolled_courses: 34,
    age: 7,
    date_enrolled: "19/12/2022",
  },
  {
    id: 163,
    name: "Reese Campos",
    enrolled_courses: 34,
    age: 8,
    date_enrolled: "23/5/2022",
  },
  {
    id: 164,
    name: "Nia Walsh",
    enrolled_courses: 35,
    age: 7,
    date_enrolled: "3/6/2020",
  },
  {
    id: 165,
    name: "Trinity Duran",
    enrolled_courses: 35,
    age: 8,
    date_enrolled: "18/8/2020",
  },
  {
    id: 166,
    name: "Steve Walter",
    enrolled_courses: 35,
    age: 6,
    date_enrolled: "25/6/2020",
  },
  {
    id: 167,
    name: "Camille Orr",
    enrolled_courses: 35,
    age: 8,
    date_enrolled: "16/11/2022",
  },
  {
    id: 168,
    name: "Bradyn Tapia",
    enrolled_courses: 35,
    age: 6,
    date_enrolled: "7/5/2021",
  },
  {
    id: 169,
    name: "Danielle Coffey",
    enrolled_courses: 35,
    age: 8,
    date_enrolled: "3/9/2020",
  },
  {
    id: 170,
    name: "Xavier Conner",
    enrolled_courses: 35,
    age: 7,
    date_enrolled: "17/10/2023",
  },
  {
    id: 171,
    name: "Emilee Sims",
    enrolled_courses: 35,
    age: 6,
    date_enrolled: "20/9/2022",
  },
  {
    id: 172,
    name: "Kian Crosby",
    enrolled_courses: 35,
    age: 8,
    date_enrolled: "2/4/2021",
  },
  {
    id: 173,
    name: "Skyler Rowe",
    enrolled_courses: 35,
    age: 6,
    date_enrolled: "8/4/2021",
  },
  {
    id: 174,
    name: "Deanna Case",
    enrolled_courses: 36,
    age: 53,
    date_enrolled: "26/4/2022",
  },
  {
    id: 175,
    name: "Keyon Morrow",
    enrolled_courses: 36,
    age: 34,
    date_enrolled: "10/2/2021",
  },
  {
    id: 176,
    name: "Hugh Key",
    enrolled_courses: 36,
    age: 63,
    date_enrolled: "12/11/2021",
  },
  {
    id: 177,
    name: "Bobby Hartman",
    enrolled_courses: 37,
    age: 65,
    date_enrolled: "24/5/2022",
  },
  {
    id: 178,
    name: "Nicole Snow",
    enrolled_courses: 37,
    age: 56,
    date_enrolled: "19/4/2023",
  },
  {
    id: 179,
    name: "Yurem Nielsen",
    enrolled_courses: 37,
    age: 67,
    date_enrolled: "15/11/2022",
  },
  {
    id: 180,
    name: "Malcolm Randolph",
    enrolled_courses: 37,
    age: 46,
    date_enrolled: "24/12/2022",
  },
  {
    id: 181,
    name: "Yurem Michael",
    enrolled_courses: 37,
    age: 36,
    date_enrolled: "2/9/2022",
  },
  {
    id: 182,
    name: "Justice Chapman",
    enrolled_courses: 37,
    age: 76,
    date_enrolled: "26/12/2023",
  },
  {
    id: 183,
    name: "Oliver Barton",
    enrolled_courses: 37,
    age: 66,
    date_enrolled: "19/4/2021",
  },
  {
    id: 184,
    name: "Zander Watson",
    enrolled_courses: 37,
    age: 30,
    date_enrolled: "15/3/2020",
  },
  {
    id: 185,
    name: "Madilyn Hood",
    enrolled_courses: 38,
    age: 6,
    date_enrolled: "27/7/2020",
  },
  {
    id: 186,
    name: "Kayleigh Mills",
    enrolled_courses: 38,
    age: 8,
    date_enrolled: "9/8/2021",
  },
  {
    id: 187,
    name: "Stacy Deleon",
    enrolled_courses: 38,
    age: 7,
    date_enrolled: "21/1/2022",
  },
  {
    id: 188,
    name: "Corinne Little",
    enrolled_courses: 39,
    age: 10,
    date_enrolled: "19/2/2021",
  },
  {
    id: 189,
    name: "Anika Mullins",
    enrolled_courses: 39,
    age: 11,
    date_enrolled: "4/4/2023",
  },
  {
    id: 190,
    name: "Jazlyn Cobb",
    enrolled_courses: 39,
    age: 11,
    date_enrolled: "23/2/2022",
  },
  {
    id: 191,
    name: "Evan Weaver",
    enrolled_courses: 39,
    age: 10,
    date_enrolled: "11/3/2022",
  },
  {
    id: 192,
    name: "Damien Pugh",
    enrolled_courses: 39,
    age: 10,
    date_enrolled: "19/6/2023",
  },
  {
    id: 193,
    name: "Louis Hardin",
    enrolled_courses: 39,
    age: 9,
    date_enrolled: "6/8/2023",
  },
  {
    id: 194,
    name: "Louis Hardin",
    enrolled_courses: 39,
    age: 9,
    date_enrolled: "6/8/2023",
  },
  {
    id: 195,
    name: "Louis Hardin",
    enrolled_courses: 39,
    age: 9,
    date_enrolled: "6/8/2023",
  },
  {
    id: 196,
    name: "Louis Hardin",
    enrolled_courses: 39,
    age: 9,
    date_enrolled: "6/8/2023",
  },
  {
    id: 197,
    name: "Louis Hardin",
    enrolled_courses: 39,
    age: 9,
    date_enrolled: "6/8/2023",
  },
  {
    id: 198,
    name: "Louis Hardin",
    enrolled_courses: 39,
    age: 9,
    date_enrolled: "6/8/2023",
  },
];

function createListStudents() {
  // https://www.randomlists.com/random-names?qty=203
  const listOfNames = [
    "Aimee Floyd",
    "Craig Simpson",
    "Darnell Brock",
    "Izaiah Bradford",
    "Angel Spencer",
    "Hazel Rowland",
    "Paul Sherman",
    "Dayami Buck",
    "Maci Baker",
    "Kyan Clay",
    "Brycen Montes",
    "Bronson Kelley",
    "Immanuel Calhoun",
    "Giada Hale",
    "Sincere Perkins",
    "Miah Baird",
    "Rosa Coleman",
    "Matias Anderson",
    "Cristian Haynes",
    "Justice Molina",
    "Felicity Haas",
    "Carter Romero",
    "Marie Whitney",
    "Davion May",
    "Coleman Holloway",
    "Vaughn Madden",
    "Lucy Villegas",
    "Shayna Higgins",
    "Levi Davis",
    "Garrett Cummings",
    "Bradyn Brooks",
    "Joel Estrada",
    "Gideon Blackwell",
    "Reid Munoz",
    "Dashawn Delacruz",
    "Emilee David",
    "Isabela Vaughn",
    "Efrain Beasley",
    "Makai Page",
    "Gavin Hopkins",
    "Miracle Cole",
    "Enrique Weaver",
    "Karsyn Rogers",
    "Jocelyn Tran",
    "Dylan Boyer",
    "Michaela Velasquez",
    "Tony Pennington",
    "August Stafford",
    "Jax Vargas",
    "Finley Richardson",
    "Fletcher Ritter",
    "Theodore Rowland",
    "Jamar Jarvis",
    "Diana Hogan",
    "Rory Hammond",
    "Jasper Munoz",
    "Hadley Pugh",
    "Saul Pearson",
    "Yazmin Campos",
    "Nico Stone",
    "Jocelynn Odonnell",
    "Kaylie Fitzpatrick",
    "Charlie Holloway",
    "Savannah Leach",
    "Zachery Chapman",
    "Emelia Doyle",
    "Kenley Rodgers",
    "Davon Mckinney",
    "Haylee Summers",
    "Giana Pacheco",
    "Regan Decker",
    "Paityn Mcdaniel",
    "Amelie Hernandez",
    "Kyra Aguilar",
    "Tiara Valencia",
    "Madisyn Hobbs",
    "Casey Benson",
    "Jaylene Schroeder",
    "Remington Little",
    "Nyla Wolfe",
    "Angel Harmon",
    "Lincoln Mckay",
    "Eliza Yates",
    "Kasey Sparks",
    "Hailey Kline",
    "Paityn Juarez",
    "Keira Hanson",
    "Trace Cardenas",
    "Wade Durham",
    "Cory Owens",
    "Angela Salas",
    "Jonathon Jennings",
    "Brenton Anthony",
    "Alisa Randall",
    "Jesse Bradford",
    "Dayami Underwood",
    "Amelie Jensen",
    "Ezekiel Berry",
    "Sage Sampson",
    "Baylee Carr",
    "Kamari Ruiz",
    "Van Andersen",
    "Jazmyn Boyle",
    "Carson Norton",
    "Meredith Orozco",
    "Arjun Kennedy",
    "Stephany Carlson",
    "Jesse Lin",
    "Eric Baird",
    "Ronnie Hardy",
    "Jayda Allison",
    "Angel Adkins",
    "Kinley Pearson",
    "Evelyn Saunders",
    "Ashlyn Bennett",
    "Franklin Haas",
    "Harmony Lowery",
    "Omari Santana",
    "Janet Ferguson",
    "Adonis Mcclure",
    "Dustin Garcia",
    "Gemma Henderson",
    "Selina Schmitt",
    "Luca Walters",
    "River Spencer",
    "Dominique Baker",
    "Adriel Patel",
    "Paige Summers",
    "Caleb Rios",
    "Ariel Lopez",
    "Sheldon Cain",
    "Janiyah Oneal",
    "Reese Campos",
    "Nia Walsh",
    "Trinity Duran",
    "Steve Walter",
    "Camille Orr",
    "Bradyn Tapia",
    "Danielle Coffey",
    "Xavier Conner",
    "Emilee Sims",
    "Kian Crosby",
    "Skyler Rowe",
    "Deanna Case",
    "Keyon Morrow",
    "Hugh Key",
    "Bobby Hartman",
    "Nicole Snow",
    "Yurem Nielsen",
    "Malcolm Randolph",
    "Yurem Michael",
    "Justice Chapman",
    "Oliver Barton",
    "Zander Watson",
    "Madilyn Hood",
    "Kayleigh Mills",
    "Stacy Deleon",
    "Corinne Little",
    "Anika Mullins",
    "Jazlyn Cobb",
    "Evan Weaver",
    "Damien Pugh",
    "Louis Hardin",
    "Leila Odom",
    "Emmy Martin",
    "Julio Ramirez",
    "Melanie Nash",
    "Talan Hatfield",
    "Dallas Owens",
    "Meredith Frederick",
    "Elsa Ali",
    "Jaslyn Bradford",
    "Raegan Barry",
    "Danielle Berg",
    "Haiden Berg",
    "Darian Scott",
    "Jesus Potter",
    "Gregory Valencia",
    "Amelia Nicholson",
    "Audrey Carlson",
    "Macie Ferguson",
    "Chace Ashley",
    "Shyann Gaines",
    "Ansley Curtis",
    "Skyler Oconnor",
    "Sarahi Whitaker",
    "Clara Olson",
    "Christina Yu",
    "Hanna Wolf",
    "Adrian Delgado",
    "Peyton Haley",
    "Corinne Holden",
    "Devon Kirk",
    "Makena Dickerson",
    "Aliyah Welch",
    "Akira Singleton",
    "Yasmine Duarte",
    "Jaylan Clements",
    "Geovanni Shaw",
    "Jaeden Abbott",
    "Solomon Mcguire",
    "Thalia Velez",
    "Justice Flynn",
  ];
  let startingIndex = 4;
  let nameIndex = 0;
  let minAge = 0;
  let maxAge = 0;
  let studentsCount = 0;
  let studentId = 31;
  classes.map((clas) => {
    if (clas.id > startingIndex) {
      if (clas.status === CLASS_STATUS.ACTIVE) {
        const name = clas.name.substring(0, clas.name.indexOf(""));
        studentsCount = studentsCount + clas.numb_students;
        for (let index = 0; index < clas.numb_students; index++) {
          switch (name) {
            case "Kinder":
              minAge = 3;
              maxAge = 6;
              break;
            case "Kids":
              minAge = 6;
              maxAge = 8;
              break;
            case "Tweens":
              minAge = 9;
              maxAge = 11;
              break;
            case "Teens":
              minAge = 12;
              maxAge = 14;
              break;

            default:
              minAge = 14;
              maxAge = 80;
              break;
          }
          const studentName = listOfNames[nameIndex];
          const studentAge =
            Math.round(Math.random() * (maxAge - minAge)) + minAge;
          const sDay = Math.round(Math.random() * 27) + 1;
          const sMonth = Math.round(Math.random() * 12) + 1;
          const sYear = Math.round(Math.random() * (2023 - 2020)) + 2020;
          console.log(
            `{id:${studentId}, name: "${studentName}",enrolled_courses:${clas.id},age:${studentAge}, date_enrolled:"${sDay}/${sMonth}/${sYear}},"`
          );
          nameIndex++;
          studentId++;
        }
      }
    }
  });
}

// createListStudents();
