import React, { useState, createContext } from "react";

export const DatabaseContext = createContext();
const LOCAL_STORAGE_KEYS = {
  STAFF: "staff",
  STUDENTS: "students",
  CLASSES: "classes",
};
const SCHOOL_POSITION = { TEACHER: "Teacher", COORDINATOR: "Coordinator" };
export const CLASS_STATUS = {
  ACTIVE: "Active",
  FINISHED: "Finished",
  CANCELED: "Canceled",
};


// TODO(Gionave): diversify the classes and codes, each code HAS to be unique to work as an ID
// TODO(Gionave): Create a shortcut for the context snippet

const classes = [
  {
    id: 0,
    name: "Book 2",
    code: "54-54",
    time: "Thursday, 12-2 PM",
    numb_students: 4,
    enrolled_students_ids: [],
    lesson: 22,
    date_start: "4/7/2023",
    date_end: "4/7/2024",
    status: CLASS_STATUS.ACTIVE,
    teacher: 1,
  },
  {
    id: 1,
    name: "Tweens 1",
    code: "54-54",
    time: "Friday, 4-6 PM",
    numb_students: 8,
    enrolled_students_ids: [],
    lesson: 25,
    date_start: "25/7/2022",
    date_end: "25/7/2023",
    status: CLASS_STATUS.ACTIVE,
    teacher: 1,
  },
  {
    id: 2,
    name: "Kids 5",
    code: "54-54",
    time: "Thursday, 4-6 PM",
    numb_students: 10,
    enrolled_students_ids: [],
    lesson: 22,
    date_start: "13/13/2023",
    date_end: "13/13/2024",
    status: CLASS_STATUS.ACTIVE,
    teacher: 1,
  },
  {
    id: 3,
    name: "Tweens 4",
    code: "54-54",
    time: "Saturday, 4-6 PM",
    numb_students: 9,
    enrolled_students_ids: [],
    lesson: 18,
    date_start: "15/11/2020",
    date_end: "15/11/2021",
    status: CLASS_STATUS.ACTIVE,
    teacher: 1,
  },
  {
    id: 4,
    name: "Book 1",
    code: "88-83",
    time: "Monday, 8-10 AM",
    numb_students: 0,
    enrolled_students_ids: [],
    lesson: 30,
    date_start: "23/05/2023",
    date_end: "31/10/2023",
    status: CLASS_STATUS.FINISHED,
    teacher: 1,
  },
  {
    id: 5,
    name: "Book 1",
    code: "87-05",
    time: "Tuesday, 8-10 AM",
    numb_students: 0,
    enrolled_students_ids: [],
    lesson: 3,
    date_start: "23/05/2023",
    date_end: "31/10/2023",
    status: CLASS_STATUS.CANCELED,
    teacher: 1,
  },
  {
    id: 6,
    name: "Kids 2",
    code: "77-96",
    time: "Wednesday, 8-10 AM",
    numb_students: 0,
    enrolled_students_ids: [],
    lesson: 3,
    date_start: "23/05/2023",
    date_end: "31/10/2023",
    status: CLASS_STATUS.CANCELED,
    teacher: 1,
  },
  {
    id: 7,
    name: "Kids 1",
    code: "50-13",
    time: "Tuesday, 4-6PM",
    numb_students: 4,
    enrolled_students_ids: [],
    lesson: 28,
    date_start: "23/05/2023",
    date_end: "31/10/2023",
    status: CLASS_STATUS.ACTIVE,
    teacher: 1,
  },
  {
    id: 8,
    name: "Kids 3",
    code: "93-15",
    time: "Friday, 10-12PM",
    numb_students: 5,
    enrolled_students_ids: [],
    lesson: 12,
    date_start: "23/05/2023",
    date_end: "31/10/2023",
    status: CLASS_STATUS.ACTIVE,
    teacher: 1,
  },
  {
    id: 9,
    name: "Kids 5",
    code: "26-52",
    time: "Friday, 10-12PM",
    numb_students: 7,
    enrolled_students_ids: [],
    lesson: 12,
    date_start: "23/05/2023",
    date_end: "31/10/2023",
    status: CLASS_STATUS.ACTIVE,
    teacher: 1,
  },
  {
    id: 10,
    name: "Advanced 1",
    code: "75-69",
    time: "Tuesday, 8-10 AM",
    numb_students: 10,
    enrolled_students_ids: [],
    lesson: 20,
    date_start: "8/6/2021",
    date_end: "8/6/2022",
    status: CLASS_STATUS.ACTIVE,
    teacher: 1,
  },
  {
    id: 11,
    name: "Teens 3",
    code: "75-69",
    time: "Saturday, 4-6 PM",
    numb_students: 8,
    enrolled_students_ids: [],
    lesson: 23,
    date_start: "6/2/2022",
    date_end: "6/2/2023",
    status: CLASS_STATUS.ACTIVE,
    teacher: 1,
  },
  {
    id: 12,
    name: "Teens 4",
    code: "75-69",
    time: "Saturday, 12-2 PM",
    numb_students: 5,
    enrolled_students_ids: [],
    lesson: 16,
    date_start: "10/6/2020",
    date_end: "10/6/2021",
    status: CLASS_STATUS.ACTIVE,
    teacher: 1,
  },
  {
    id: 13,
    name: "Book 1",
    code: "75-69",
    time: "Saturday, 10-12 PM",
    numb_students: 5,
    enrolled_students_ids: [],
    lesson: 12,
    date_start: "19/2/2021",
    date_end: "19/2/2022",
    status: CLASS_STATUS.ACTIVE,
    teacher: 1,
  },
  {
    id: 14,
    name: "Tweens 2",
    code: "75-69",
    time: "Saturday, 2-4 PM",
    numb_students: 4,
    enrolled_students_ids: [],
    lesson: 24,
    date_start: "8/9/2021",
    date_end: "8/9/2022",
    status: CLASS_STATUS.ACTIVE,
    teacher: 1,
  },
  {
    id: 15,
    name: "Keep Talking 2",
    code: "75-69",
    time: "Friday, 2-4 PM",
    numb_students: 10,
    enrolled_students_ids: [],
    lesson: 4,
    date_start: "14/5/2020",
    date_end: "14/5/2021",
    status: CLASS_STATUS.ACTIVE,
    teacher: 1,
  },
  {
    id: 16,
    name: "Tweens 4",
    code: "75-69",
    time: "Wednesday, 4-6 PM",
    numb_students: 3,
    enrolled_students_ids: [],
    lesson: 4,
    date_start: "5/4/2021",
    date_end: "5/4/2022",
    status: CLASS_STATUS.ACTIVE,
    teacher: 1,
  },
  {
    id: 17,
    name: "Book 2",
    code: "75-69",
    time: "Friday, 8-10 AM",
    numb_students: 6,
    enrolled_students_ids: [],
    lesson: 4,
    date_start: "4/3/2021",
    date_end: "4/3/2022",
    status: CLASS_STATUS.ACTIVE,
    teacher: 1,
  },
  {
    id: 18,
    name: "Kids 2",
    code: "75-69",
    time: "Tuesday, 2-4 PM",
    numb_students: 9,
    enrolled_students_ids: [],
    lesson: 24,
    date_start: "10/11/2020",
    date_end: "10/11/2021",
    status: CLASS_STATUS.ACTIVE,
    teacher: 1,
  },
  {
    id: 19,
    name: "Teens 3",
    code: "75-69",
    time: "Thursday, 12-2 PM",
    numb_students: 4,
    enrolled_students_ids: [],
    lesson: 9,
    date_start: "15/10/2021",
    date_end: "15/10/2022",
    status: CLASS_STATUS.ACTIVE,
    teacher: 1,
  },
  {
    id: 20,
    name: "Advanced 2",
    code: "75-69",
    time: "Tuesday, 2-4 PM",
    numb_students: 7,
    enrolled_students_ids: [],
    lesson: 11,
    date_start: "10/4/2022",
    date_end: "10/4/2023",
    status: CLASS_STATUS.ACTIVE,
    teacher: 1,
  },
  {
    id: 21,
    name: "Kids 5",
    code: "75-69",
    time: "Tuesday, 4-6 PM",
    numb_students: 8,
    enrolled_students_ids: [],
    lesson: 4,
    date_start: "9/12/2020",
    date_end: "9/12/2021",
    status: CLASS_STATUS.ACTIVE,
    teacher: 1,
  },
  {
    id: 22,
    name: "Kids 4",
    code: "75-69",
    time: "Friday, 8-10 PM",
    numb_students: 8,
    enrolled_students_ids: [],
    lesson: 19,
    date_start: "13/10/2021",
    date_end: "13/10/2022",
    status: CLASS_STATUS.ACTIVE,
    teacher: 1,
  },
  {
    id: 23,
    name: "Kids 4",
    code: "75-69",
    time: "Wednesday, 2-4 PM",
    numb_students: 3,
    enrolled_students_ids: [],
    lesson: 27,
    date_start: "19/6/2021",
    date_end: "19/6/2022",
    status: CLASS_STATUS.ACTIVE,
    teacher: 1,
  },
  {
    id: 24,
    name: "Keep Talking 2",
    code: "75-69",
    time: "Wednesday, 4-6 PM",
    numb_students: 4,
    enrolled_students_ids: [],
    lesson: 4,
    date_start: "28/11/2021",
    date_end: "28/11/2022",
    status: CLASS_STATUS.ACTIVE,
    teacher: 1,
  },
  {
    id: 25,
    name: "Advanced 2",
    code: "75-69",
    time: "Thursday, 12-2 PM",
    numb_students: 5,
    enrolled_students_ids: [],
    lesson: 15,
    date_start: "12/8/2021",
    date_end: "12/8/2022",
    status: CLASS_STATUS.ACTIVE,
    teacher: 1,
  },
  {
    id: 26,
    name: "Teens 1",
    code: "75-69",
    time: "Thursday, 4-6 PM",
    numb_students: 5,
    enrolled_students_ids: [],
    lesson: 2,
    date_start: "16/13/2022",
    date_end: "16/13/2023",
    status: CLASS_STATUS.ACTIVE,
    teacher: 1,
  },
  {
    id: 27,
    name: "Tweens 3",
    code: "75-69",
    time: "Thursday, 4-6 PM",
    numb_students: 7,
    enrolled_students_ids: [],
    lesson: 14,
    date_start: "3/11/2020",
    date_end: "3/11/2021",
    status: CLASS_STATUS.ACTIVE,
    teacher: 1,
  },
  {
    id: 28,
    name: "Advanced 2",
    code: "75-69",
    time: "Friday, 6-8 PM",
    numb_students: 4,
    enrolled_students_ids: [],
    lesson: 13,
    date_start: "10/4/2021",
    date_end: "10/4/2022",
    status: CLASS_STATUS.ACTIVE,
    teacher: 1,
  },
  {
    id: 29,
    name: "Book 2",
    code: "75-69",
    time: "Saturday, 6-8 PM",
    numb_students: 8,
    enrolled_students_ids: [],
    lesson: 23,
    date_start: "17/3/2021",
    date_end: "17/3/2022",
    status: CLASS_STATUS.ACTIVE,
    teacher: 1,
  },
  {
    id: 30,
    name: "Book 1",
    code: "75-69",
    time: "Thursday, 4-6 PM",
    numb_students: 4,
    enrolled_students_ids: [],
    lesson: 3,
    date_start: "7/7/2023",
    date_end: "7/7/2024",
    status: CLASS_STATUS.ACTIVE,
    teacher: 1,
  },
  {
    id: 31,
    name: "Book 4",
    code: "75-69",
    time: "Monday, 4-6 PM",
    numb_students: 5,
    enrolled_students_ids: [],
    lesson: 8,
    date_start: "8/2/2021",
    date_end: "8/2/2022",
    status: CLASS_STATUS.ACTIVE,
    teacher: 1,
  },
  {
    id: 32,
    name: "Tweens 1",
    code: "75-69",
    time: "Monday, 4-6 PM",
    numb_students: 7,
    enrolled_students_ids: [],
    lesson: 14,
    date_start: "4/5/2023",
    date_end: "4/5/2024",
    status: CLASS_STATUS.ACTIVE,
    teacher: 1,
  },
  {
    id: 33,
    name: "Kids 3",
    code: "75-69",
    time: "Thursday, 2-4 PM",
    numb_students: 4,
    enrolled_students_ids: [],
    lesson: 2,
    date_start: "13/12/2022",
    date_end: "13/12/2023",
    status: CLASS_STATUS.ACTIVE,
    teacher: 1,
  },
  {
    id: 34,
    name: "Kids 1",
    code: "75-69",
    time: "Thursday, 12-2 PM",
    numb_students: 9,
    enrolled_students_ids: [],
    lesson: 20,
    date_start: "17/7/2021",
    date_end: "17/7/2022",
    status: CLASS_STATUS.ACTIVE,
    teacher: 1,
  },
  {
    id: 35,
    name: "Kids 2",
    code: "75-69",
    time: "Thursday, 12-2 PM",
    numb_students: 10,
    enrolled_students_ids: [],
    lesson: 16,
    date_start: "18/12/2023",
    date_end: "18/12/2024",
    status: CLASS_STATUS.ACTIVE,
    teacher: 1,
  },
  {
    id: 36,
    name: "Book 1",
    code: "75-69",
    time: "Monday, 10-12 PM",
    numb_students: 3,
    enrolled_students_ids: [],
    lesson: 3,
    date_start: "13/5/2020",
    date_end: "13/5/2021",
    status: CLASS_STATUS.ACTIVE,
    teacher: 1,
  },
  {
    id: 37,
    name: "Book 4",
    code: "75-69",
    time: "Wednesday, 8-10 PM",
    numb_students: 8,
    enrolled_students_ids: [],
    lesson: 14,
    date_start: "25/5/2022",
    date_end: "25/5/2023",
    status: CLASS_STATUS.ACTIVE,
    teacher: 1,
  },
  {
    id: 38,
    name: "Kids 1",
    code: "75-69",
    time: "Friday, 6-8 PM",
    numb_students: 3,
    enrolled_students_ids: [],
    lesson: 14,
    date_start: "8/3/2021",
    date_end: "8/3/2022",
    status: CLASS_STATUS.ACTIVE,
    teacher: 1,
  },
  {
    id: 39,
    name: "Tweens 3",
    code: "75-69",
    time: "Thursday, 12-2 PM",
    numb_students: 6,
    enrolled_students_ids: [],
    lesson: 20,
    date_start: "5/11/2023",
    date_end: "5/11/2024",
    status: CLASS_STATUS.ACTIVE,
    teacher: 1,
  },
];
const staff = [
  {
    id: 1,
    name: "Gionave",
    position: SCHOOL_POSITION.TEACHER,
    classes: [0, 1, 2, 3],
  },
  {
    id: 2,
    name: "Antares",
    position: SCHOOL_POSITION.TEACHER,
    classes: [0, 1, 2, 3],
  },
];

const students = [
  { id: 0, name: "Macaulay Morgana", enrolled_courses: [] },
  { id: 1, name: "Marion Kristie", enrolled_courses: [] },
  { id: 2, name: "Winton Kayden", enrolled_courses: [] },
  { id: 3, name: "Gibson Bethel", enrolled_courses: [] },
  { id: 4, name: "Suellen Albie", enrolled_courses: [] },
  { id: 5, name: "Weldon Jennie", enrolled_courses: [] },
  { id: 6, name: "Grier Annabella", enrolled_courses: [] },
  { id: 7, name: "Elicia Candice", enrolled_courses: [] },
  { id: 8, name: "Leigh Jon", enrolled_courses: [] },
  { id: 9, name: "Caylee Addy", enrolled_courses: [] },
  { id: 10, name: "Rosanna Quintin", enrolled_courses: [] },
  { id: 11, name: "Nyah Gaby", enrolled_courses: [] },
  { id: 12, name: "Deidre Elfrieda", enrolled_courses: [] },
  { id: 13, name: "Woody Clement", enrolled_courses: [] },
  { id: 14, name: "Alexus Jream", enrolled_courses: [] },
  { id: 15, name: "Lemoine Saige", enrolled_courses: [] },
  { id: 16, name: "Reed Tiana", enrolled_courses: [] },
  { id: 17, name: "Karter Leone", enrolled_courses: [] },
  { id: 18, name: "Buzz Hall", enrolled_courses: [] },
  { id: 19, name: "Andy Kelsey", enrolled_courses: [] },
  { id: 20, name: "Amy Florry", enrolled_courses: [] },
  { id: 21, name: "Julianne Paulette", enrolled_courses: [] },
  { id: 22, name: "Flower Hewie", enrolled_courses: [] },
  { id: 23, name: "Rebeccanne Sanford", enrolled_courses: [] },
  { id: 24, name: "Julie Hadley", enrolled_courses: [] },
  { id: 25, name: "Rafferty Calista", enrolled_courses: [] },
  { id: 26, name: "Rodolph Sid", enrolled_courses: [] },
  { id: 27, name: "Watson Emersyn", enrolled_courses: [] },
  { id: 28, name: "Placid Ashlynn", enrolled_courses: [] },
  { id: 29, name: "Lorri Laurinda", enrolled_courses: [] },
];

export const DatabaseContextProvider = (props) => {
  function randomCode() {
    const classes = [
      "Kids 1",
      "Kids 2",
      "Kids 3",
      "Kids 4",
      "Kids 5",
      "Tweens 1",
      "Tweens 2",
      "Tweens 3",
      "Tweens 4",
      "Teens 1",
      "Teens 2",
      "Teens 3",
      "Teens 4",
      "Teens 5",
      "Book 1",
      "Book 2",
      "Book 3",
      "Book 4",
      "Keep Talking 1",
      "Keep Talking 2",
      "Keep Talking 3",
      "Advanced 1",
      "Advanced 2",
      "Advanced 3",
    ];
    const time = [
      "8-10 AM",
      "10-12 PM",
      "12-2 PM",
      "2-4 PM",
      "4-6 PM",
      "6-8 PM",
      "8-10 PM",
    ];
    const code = `${Math.round(Math.random() * 9)}${Math.round(
      Math.random() * 9
    )}-${Math.round(Math.random() * 9)}${Math.round(Math.random() * 9)}`;
    const day = [
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Thursday",
      "Friday",
      "Saturday",
    ];

    for (let index = 0; index < 4; index++) {
      const sDay = Math.round(Math.random() * 27) + 1;
      const sMonth = Math.round(Math.random() * 12) + 1;
      const sYear = Math.round(Math.random() * (2023 - 2020)) + 2020;
      console.log(`
    {id: ${index},
    name: '${classes[Math.floor(Math.random() * classes.length)]}',
    code: '${code}',
    time: '${day[Math.floor(Math.random() * day.length)]}, ${
        time[Math.floor(Math.random() * time.length)]
      }',
    numb_students: ${Math.round(Math.random() * 7) + 3},
    enrolled_students_ids: [],
    lesson: ${Math.round(Math.random() * 27) + 1},
    date_start: '${sDay}/${sMonth}/${sYear}',
    date_end:'${sDay}/${sMonth}/${sYear + 1}',
    status: CLASS_STATUS.ACTIVE,
    teacher: 1},`);
    }
  }
  // randomCode();

  // TODO(Gionave): Populate a list of students to make them take classes

  function createInitialDBs() {
    localStorage.setItem(LOCAL_STORAGE_KEYS.STAFF, JSON.stringify(staff));
    localStorage.setItem(LOCAL_STORAGE_KEYS.STUDENTS, JSON.stringify(students));
    localStorage.setItem(LOCAL_STORAGE_KEYS.CLASSES, JSON.stringify(classes));
  }

  function getDataFromKey(key) {
    return JSON.parse(localStorage.getItem(key));
  }

  const getClassesDataFromStaffId = (id) => {
    const classesData = getDataFromKey(LOCAL_STORAGE_KEYS.CLASSES);

    const data = classesData.filter((classData) => classData.teacher === id);
    return data;
  };

  return (
    <DatabaseContext.Provider
      value={{
        SCHOOL_POSITION,
        LOCAL_STORAGE_KEYS,
        CLASS_STATUS,
        createInitialDBs,
        getDataFromKey,
        getClassesDataFromStaffId,
      }}
    >
      {props.children}
    </DatabaseContext.Provider>
  );
};
